ChatApp/urls.py
from django.contrib import admin
from django.urls import path, include
from app.views import HomeView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
	path('', HomeView.as_view(), name='home'),
	path('account/', include('account.urls', namespace='account')),
	path('friend/', include('friend.urls', namespace='friend')),
	path('chat/', include('chat.urls', namespace='chat')),
	path('group/', include('chat.urls', namespace='group')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

account/urls.py
from django.urls import path
from django.contrib.auth.views import (
	PasswordResetDoneView,
	PasswordResetCompleteView
)
from .views import (
	RegisterView,
	ProfileView,
	CustomLoginView,
	CustomLogoutView,
	CustomPasswordResetView,
	CustomPasswordResetConfirmView,
	CustomPasswordChangeView,
	CustomPasswordChangeDoneView,
	ProfileEditView,
	SearchView
)

app_name = 'account'

urlpatterns = [
	path('login/', CustomLoginView.as_view(), name='login'),

	path('logout/', CustomLogoutView.as_view(), name='logout'),

	path('register/', RegisterView.as_view(), name='register'),

	path('search/', SearchView.as_view(), name='search'),

	path('profile/<str:username>/',
        ProfileView.as_view(),
		name='profile'
	),

    path('edit/<str:username>/',
		ProfileEditView.as_view(),
		name='edit'
	),

    path(
        'password-change/',
		CustomPasswordChangeView.as_view(),
		name='password_change'
    ),

    path(
        'password-change/done/',
        CustomPasswordChangeDoneView.as_view(),
        name='password_change_done',
    ),

    path('password-reset/',
		CustomPasswordResetView.as_view(),
		name='password_reset'
	),

    path(
        'password-reset/done/',
        PasswordResetDoneView.as_view(),
        name='password_reset_done',
    ),

    path(
        'reset/<uidb64>/<token>/',
        CustomPasswordResetConfirmView.as_view(),
        name='password_reset_confirm',
    ),

    path(
        'reset/done/',
        PasswordResetCompleteView.as_view(),
        name='password_reset_complete',
    )
]

chat/urls.py
from django.urls import path
from .views import (
	IndexChatView,
	PersonalChatView,
	GroupChatView
)

app_name = 'chat'

urlpatterns = [
	path('', IndexChatView.as_view(), name='index'),
	path('personal/', PersonalChatView.as_view(), name='personal'),
	path('group/', GroupChatView.as_view(), name='group'),
]

templates/snippets/footer.html
<footer class="pb-3">
	<ul class="nav justify-content-center mb-3 border-bottom">
		<li class="nav-item">
			<a href="{% url 'home' %}" class="nav-link text-body-secondary">Home</a>
		</li>
		<li class="nav-item">
			<a href="#" class="nav-link text-body-secondary">Features</a>
		</li>
		<li class="nav-item">
			<a href="#" class="nav-link text-body-secondary">Pricing</a>
		</li>
		<li class="nav-item">
			<a href="#" class="nav-link text-body-secondary">FAQs</a>
		</li>
		<li class="nav-item">
			<a href="#" class="nav-link text-body-secondary">About</a>
		</li>
	</ul>
	<p class="text-center mt-3 m-0 text-body-secondary year">ChatApp, Inc</p>
	<script>
		document.querySelector("p.year").innerText += ` © ${new Date().getFullYear()}`;
	</script>
</footer>

templates/snippets/header.html
<style>
	.dropdown-toggle::after {
		display: none;
	}

	.dropdown-item:active {
		background-color: var(--bs-body-color);
	}
</style>
<header class="p-3 shadow-lg sticky-top mb-3">
	<div class="bs5-container-fluid">
		<div class="row justify-content-center justify-content-md-between justify-content-lg-between">
			<div class="col-md-6 col-lg-6 col-12 d-flex flex-md-row flex-lg-row flex-row justify-content-between justify-content-md-start mb-md-0 mb-lg-0 mb-3">
				<a class="fs-4 me-md-5 me-lg-5 mb-md-0 mb-lg-0" href="/">ChatApp</a>
				{% if request.user.is_authenticated %}
				<div class="position-relative col-6 col-md-6 col-lg-3">
					<form autocomplete="off" role="search" method="post">
						<div class="input-group">
							<input class="form-control" type="search" name="search" id="user_search"
								placeholder="Search User" maxlength="10" />
							<div class="input-group-text user-select-none px-2">
								<span class="material-icons">search</span>
							</div>
						</div>
					</form>
					<div class="position-absolute d-none flex-column align-items-center justify-content-between z-3">
						<ul id="search_result" class="list-group"></ul>
						<div id="pagination_controls"
							class="pagination-controls d-flex align-items-center justify-content-between user-select-none" style="background-color: var(--bs-body-bg);">
						</div>
						<style>
							@media (max-width:768px) {
								ul#search_result + div {
									width: max-content;
									transform: translate(-12vw, 0.5vh);
								}
								ul#search_result {
									transform: translate(-12vw, 0.5vh);
								}
							}
						</style>
					</div>
				</div>
				<script>{% include 'snippets/search_user.js' %}</script>
				{% endif %}
			</div>
			<div
				class="d-flex user-select-none px-3 w-auto align-items-center">
				{% if request.user.is_authenticated %}
				<div id="notifications" class="dropdown text-end me-5">
					<button type="button" id="notif-btn" class="btn position-relative align-items-center dropdown-toggle p-1 border-0"
						data-bs-toggle="dropdown" aria-expanded="false">
						<span class="material-icons">notifications</span>
						<span id="counter"
							class="position-absolute top-0 start-100 translate-middle text-info border-0 rounded-circle"></span>
					</button>
					<ul class="dropdown-menu p-0"></ul>
					<style>
						@media (max-width:768px) {
							div#notifications > ul {
								transform: translate(-75px, 41px) !important;
							}
						}
						div#notifications > ul {
							max-height: 9rem;
							min-height: auto;
							overflow: scroll;
							width: max-content;
						}

						div#notifications > ul::-webkit-scrollbar {
							width: 0.2rem;
						}
					</style>
					<script>{% include 'snippets/notifications.js' %}</script>
				</div>
				<div class="dropdown text-end ms-5">
					<a href="#" class="d-block link-body-emphasis text-decoration-none dropdown-toggle"
						data-bs-toggle="dropdown" aria-expanded="false">
						<img src="{{request.user.profile_image.url}}" alt="User Profile Image" width="40" height="40"
							class="rounded-circle" loading="lazy" />
					</a>
					<ul class="dropdown-menu text-small">
						<li>
							<button class="dropdown-item btn">
								<a class="w-100 d-flex align-items-center justify-content-between" href="{% url 'account:profile' request.user.username %}">Profile
									<span class="material-icons">account_circle</span>
								</a>
							</button>
						</li>
						<li>
							<button
								class="dropdown-item switch-theme btn d-flex align-items-center justify-content-between">
								<span class="text-body-secondary fs-6"></span>
								<span class="material-icons"></span>
							</button>
						</li>
						<li>
							<form class="dropdown-item text-danger" action="{% url 'account:logout' %}" method="post">
								{% csrf_token %}
								<button type="submit"
									class="dropdown-item text-danger d-flex align-items-center justify-content-between p-0">LogOut
									<span class="material-icons">logout<span>
								</button>
							</form>
						</li>
					</ul>
				</div>
			</div>
			{% else %}
			<div class="d-md-flex d-lg-flex d-none w-100 justify-content-md-end">
				<a href="{% url 'account:login' %}" class="me-lg-3">
					<button type="button" class="bg-transparent border-0 d-flex align-items-center text-success">Log In
						<span class="material-icons">login</span>
					</button>
				</a>
				<a href="{% url 'account:register' %}" class="">
					<button type="button" class="bg-transparent border-0 d-flex align-items-center text-warning">Sign Up
						<span class="material-icons">person_add</span>
					</button>
				</a>
			</div>
			<div class="d-lg-none d-md-none">
				<button class="d-flex link-body-emphasis dropdown-toggle border-0 bg-transparent"
					data-bs-toggle="dropdown" aria-expanded="true">
					<span class="material-icons">menu</span>
				</button>
				<ul class="dropdown-menu text-small shadow-lg">
					<li class="mb-1">
						<a class="dropdown-item" href="{% url 'account:login' %}">
							<button type="button"
								class="bg-transparent border-0 d-flex align-items-center text-success">Log In
								<span class="material-icons ms-1">login</span>
							</button>
						</a>
					</li>
					<li>
						<a class="dropdown-item" href="{% url 'account:register' %}">
							<button type="button"
								class="bg-transparent border-0 d-flex align-items-center text-warning">Sign
								Up
								<span class="material-icons ms-1">person_add</span>
							</button>
						</a>
					</li>
				</ul>
			</div>
			{% endif %}
			<script>{% include 'snippets/change_theme.js' %}</script>
		</div>
	</div>
</header>